server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://vpn115:5432/psiot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  redis:
    host: localhost
    port: 6379
  dubbo:
    application:
      name: sso-service
      registry: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20882
