server:
  port: 8200

spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - register
      - monitor
      - server
  boot:
    admin:
      context-path: ${MONITOR_CONTEXT_PATH:/}
      ui:
        title: Admin Monitor
        public-url: ${MONITOR_PUBLIC_URL:/}
        brand: <span>Admin Monitor</span>
  devtools:
    livereload:
      port: 35730

logging:
  level:
    org.aurorae: DEBUG
  file:
    name: tmp/logs/center/monitor/${spring.application.name}.log