server:
  port: 8084
spring:
  profiles:
    include:
      - mongo
      - redis
      - mysql
  dubbo:
    application:
      name: cwl-service
      registry: zookeeper://127.0.0.1:2181
      qos-port: 22224
    protocol:
      name: dubbo
      port: 20884